### ISSUE TITLE
Minor warning lines

### ISSUE THREAD

**Issue by ACEnglish** [Jong-hun-Park/trviz#5]
Hello,

When running the tool in a loop, I get a warning that 
```
/stornext/snfs4/next-gen/scratch/english/round2/mpy/lib/python3.10/site-packages/trviz/visualizer.py:178: RuntimeWarning: More tha
n 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explic
itly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using
`matplotlib.pyplot.close()`.
```

Also, I didn't record the exact situation that gave rise to this error, or the full error, but I'm pretty sure it was during my first attempt to use the tool. I got an error that:
```
ModuleNotFoundError: No module named 'distinctipy'
```

But besides those minor hiccups trviz has been a wonderful tool and easy to use.

Have a great day,
~/Adam English

**Comment by Jong-hun-Park** [comment]
Hi @ACEnglish,

Thanks for using TRviz!

I've tried to fix the error before and added `plt.close()` at the end of the function. But, for some reason, it did not work, and I found another working solution. This commit b28a80605554b5fb2c2396850ca8093c3a44124b should fix the warning. I will release another version soon with the fix and another speed improvement.

Thanks again. It is always happy to hear feedback from real users. Let me know if you face any other issues.
