### ISSUE TITLE
Apple M1 Support

### ISSUE THREAD

**Issue by aob93** [Jong-hun-Park/trviz#6]
Hi, congrats on what looks like a really useful package. 
Installation is currently erroring out with "error: unknown target CPU 'apple-m1"
I wonder if apple silicon support is something that could be added, or should I look into some kind of containerised workflow. 
Thanks!

**Comment by Jong-hun-Park** [comment]
Hi @aob93, 

Thanks for submitting the issue.

The error is caused by to recent update for speeding up the decomposition algorithm.
I will release a fixed version soon and let you know once it's ready.

**Comment by Jong-hun-Park** [comment]
Hi @aob93,

I've added a --no-cython flag for installation. Can you try installing trviz again from github?

Here are the directions you may want:
```
git clone https://github.com/Jong-hun-Park/trviz.git

cd trviz/

python setup.py install --no-cython
```

**Comment by aob93** [comment]
Looks like it's working now. Many thanks!

**Comment by Jong-hun-Park** [comment]
Thanks for testing!
